# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Rekt Coder Blog

# Permalinks
permalink:           pretty

# Setup
title:               RektCoder
url:                 http://rektcoder.github.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:             Rekt Coder
  
pages_list:       
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
